# Generated by Django 2.2.12 on 2020-06-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
